In [2]:
import cv2            
import glob

In [3]:
sink_video_path = glob.glob('fullframe_data/*sink.mp4')[0]           
source_video_path = glob.glob('fullframe_data/*source.mp4')[0]

In [4]:
sink = cv2.VideoCapture(sink_video_path)
source = cv2.VideoCapture(source_video_path)
count = 0

while True:
    ret, source_frame = source.read()
    ret, sink_frame = sink.read()
    if not ret:
        break
    count += 1
    cv2.imshow("source", cv2.flip(source_frame, -1))
    cv2.imshow("sink", cv2.flip(sink_frame, -1))
    cv2.waitKey(10)                     
count
cv2.destroyAllWindows()
print(count)
sink.release()
source.release()

KeyboardInterrupt:

In [5]:
sink.release()
source.release()
cv2.destroyAllWindows()

In [108]:
import pandas as pd

In [109]:
source = pd.read_csv(source_video_path.replace(".mp4", ".txt"), header=None, names=['timestamp'])
sink = pd.read_csv(sink_video_path.replace(".mp4", ".txt"), header=None, names=['timestamp'])

In [110]:
source.head()

              timestamp
0  pts_time=9966.254494
1  pts_time=9966.321174
2  pts_time=9966.387773
3  pts_time=9966.454415
4  pts_time=9966.521052

In [111]:
sink.head()

              timestamp
0  pts_time=9966.254477
1  pts_time=9966.321135
2  pts_time=9966.387753
3  pts_time=9966.454392
4   pts_time=9966.52103

In [112]:
source.timestamp = source.timestamp.apply(lambda t: float((t.split("=")[-1])))
sink.timestamp = sink.timestamp.apply(lambda t: float((t.split("=")[-1])))

In [113]:
df = pd.concat([source, sink], axis=1)
df.columns =['source_ts', 'sink_ts']
df['delta'] = df['sink_ts'] - df['source_ts']

In [114]:
df

        source_ts       sink_ts     delta
0     9966.254494   9966.254477 -0.000017
1     9966.321174   9966.321135 -0.000039
2     9966.387773   9966.387753 -0.000020
3     9966.454415   9966.454392 -0.000023
4     9966.521052   9966.521030 -0.000022
..            ...           ...       ...
595  10005.936982  10005.936964 -0.000018
596  10006.003618  10006.003601 -0.000017
597  10006.070259  10006.070240 -0.000019
598  10006.136895  10006.136877 -0.000018
599  10006.203530  10006.203512 -0.000018

[600 rows x 3 columns]

In [2]:
9966.454415-9966.521052

-0.06663699999990058

In [116]:
df[df['delta']>0.0001]

Empty DataFrame
Columns: [source_ts, sink_ts, delta]
Index: []

In [117]:
df[df['delta']<-0.0001]

       source_ts     sink_ts     delta
483  9998.473609  9998.44027 -0.033339

In [118]:
float(df['delta'].min())

-0.033339000001433305

In [119]:
float(df['delta'].max())

-1.3999999282532372e-05