In [26]:
import pandas as pd
import os
import glob

## Go through dataset folder ("../data/labelled_golf_ball_data") and produce base_dataset.csv

In [2]:
ROOT_original_dataset = "../data/labelled_golf_ball_data"
count = 0
with open("base_dataset.csv", "w") as f:
    csv_header = f"location,swing_type,frame_type,src_video,frame_path,label_path\n"
    f.write(csv_header)
    for dir in os.listdir(ROOT_original_dataset):
        golf_ball_labelled_dir = os.path.join(ROOT_original_dataset,dir)

        for location in os.listdir(golf_ball_labelled_dir):
            
            location_dir = os.path.join(golf_ball_labelled_dir,location)
            
            for frame_type in os.listdir(location_dir):
                video_dir = os.path.join(location_dir,frame_type)
                for src_video in os.listdir(video_dir):
                    frames_dir = os.path.join(video_dir, src_video, "images")
                    labels_dir = os.path.join(video_dir, src_video, "labels")
                    for frame, label in zip(os.listdir(frames_dir),os.listdir(labels_dir)):
                        
                        frame = f"images\{frame}"
                        label = f"labels\{label}"
                        print(f"dir: {dir}")
                        print(f"    location: {location}")
                        print(f"        frame_type: {frame_type}")
                        print(f"            src_video: {src_video}")
                        print(f"                frame: {frame}")
                        print(f"                frame: {label}")
                        
                        dir
                        location
                        swing_type = dir.replace("Golf_Ball_","").replace("_data_labelled_final","")
                        frame_type
                        src_video
                        frame_path = os.path.join(dir, location, frame_type, src_video,frame)
                        label_path = os.path.join(dir, location, frame_type, src_video,label)
                        
                        csv_line = f"{location},{swing_type},{frame_type},{src_video},{frame_path},{label_path}\n"
                        f.write(csv_line)
                        count+=1
print(f"data count: {count}")

dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_10.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_10.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_1130.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_1130.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_1150.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_1150.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_1220.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_1220.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_1350.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_1350.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_1370.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_1370.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_150.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_150.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_170.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_170.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_190.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_190.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_240.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_240.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_260.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_260.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_280.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_280.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_300.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_300.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_320.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_320.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_340.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_340.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_360.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_360.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_380.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_380.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_400.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_400.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_420.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_420.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_490.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_490.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_510.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_510.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_530.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_530.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_550.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_550.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_570.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_570.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_590.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_590.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_610.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_610.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_630.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_630.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_810.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_810.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_830.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_830.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_850.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_850.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_870.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_870.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_890.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_890.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_910.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_910.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_930.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_930.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233610_sink
                frame: images\20250304_t_233610_sink_frame_right_950.jpeg
                frame: labels\20250304_t_233610_sink_frame_right_950.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1010.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1010.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1030.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1030.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1050.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1050.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1070.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1070.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1090.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1090.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_110.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_110.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1110.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1110.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1130.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1130.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1150.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1150.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1170.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1170.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1190.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1190.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1210.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1210.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1230.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1230.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1250.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1250.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1270.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1270.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1290.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1290.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_130.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_130.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1310.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1310.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1330.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1330.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1350.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1350.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1370.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1370.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1390.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1390.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1410.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1410.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1430.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1430.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1450.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1450.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1470.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1470.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1490.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1490.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_150.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_150.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_170.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_170.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames
            src_video: 20250304_t_233642_sink
                frame: images\20250304_t_233642_sink_frame_right_1880.jpeg
                frame: labels\20250304_t_233642_sink_frame_right_1880.txt
dir: Golf_Ball_Flighted_data_labelled_final
    location: KP_Common_Area
        frame_type: None_Strike_frames

In [27]:
df = pd.read_csv("./base_dataset.csv")
df['train_set'] = 0
df['val_set'] = 0
df['test_set'] = 0
df.head()

,location,swing_type,frame_type,src_video,frame_path,label_path,train_set,val_set,test_set
0,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,0
1,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,0
2,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,0
3,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,0
4,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,0

In [28]:
grouped = df.groupby("swing_type")

In [29]:
df_group = {}
for name, group in grouped:
    df_group[name] = group

In [30]:
flighted_df_group = {}
for name, group in df_group['Flighted'].groupby("location"):
    print(name)
    flighted_df_group[name] = group

KP_Common_Area
KP_Study_Area

In [31]:
putting_df_group = {}
for name, group in df_group['Putting'].groupby("location"):
    print(name)
    putting_df_group[name] = group

KP_Study_Room
PR_Library_Bottom_Floor
PR_Library_Top_Floor

## Stratefied data splitting (train-val-test) for every location (where data was collected) and for every frame type (strike_frame/non_strike_frame)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
splitted_set = pd.DataFrame(columns=df.columns)
splitted_set.head()

Empty DataFrame
Columns: [location, swing_type, frame_type, src_video, frame_path, label_path, train_set, val_set, test_set]
Index: []

In [37]:
flighted_df_group['KP_Common_Area'].head(2)

,location,swing_type,frame_type,src_video,frame_path,label_path,train_set,val_set,test_set
0,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,0
1,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,0

In [10]:
for key in flighted_df_group.keys():
    print(key)
    print(flighted_df_group[key].value_counts("frame_type"))
    print()
    for name, group in flighted_df_group[key].groupby("frame_type"):
        print(f"{name} total", group['frame_type'].count())
        # splitting here
        train, test = train_test_split(group, test_size=0.2, random_state=123)
        test, val = train_test_split(test, test_size=0.5, random_state=123)
        
        train['train_set'] = 1
        test['test_set'] = 1
        val['val_set'] = 1

        print("train", len(train))
        print('test', len(test))
        print('val', len(val))
        # re concat here
        splitted_set = pd.concat([splitted_set, train, test, val], ignore_index=True)


        
    print()
    print()

KP_Common_Area
frame_type
None_Strike_frames    473
Strike_frames         178
Name: count, dtype: int64

None_Strike_frames total 473
train 378
test 47
val 48
Strike_frames total 178
train 142
test 18
val 18


KP_Study_Area
frame_type
None_Strike_frames    480
Strike_frames          96
Name: count, dtype: int64

None_Strike_frames total 480
train 384
test 48
val 48
Strike_frames total 96
train 76
test 10
val 10

In [11]:
for key in putting_df_group.keys():
    print(key)
    print(putting_df_group[key].value_counts("frame_type"))
    print()
    for name, group in putting_df_group[key].groupby("frame_type"):
        print(f"{name} total", group['frame_type'].count())
        # splitting here
        train, test = train_test_split(group, test_size=0.2, random_state=123)
        test, val = train_test_split(test, test_size=0.5, random_state=123)
        
        train['train_set'] = 1
        test['test_set'] = 1
        val['val_set'] = 1
        
        
        print("train", len(train))
        print('test', len(test))
        print('val', len(val))
        # re concat here
        splitted_set = pd.concat([splitted_set, train, val, test], ignore_index=True)
    print()
    print()

KP_Study_Room
frame_type
None_Strike_frames    355
Strike_frames         259
Name: count, dtype: int64

None_Strike_frames total 355
train 284
test 35
val 36
Strike_frames total 259
train 207
test 26
val 26


PR_Library_Bottom_Floor
frame_type
None_Strike_frames    511
Strike_frames         361
Name: count, dtype: int64

None_Strike_frames total 511
train 408
test 51
val 52
Strike_frames total 361
train 288
test 36
val 37


PR_Library_Top_Floor
frame_type
Strike_frames         446
None_Strike_frames    432
Name: count, dtype: int64

None_Strike_frames total 432
train 345
test 43
val 44
Strike_frames total 446
train 356
test 45
val 45

In [24]:
print(f"train {splitted_set['train_set'].value_counts()[1]}")
print(f"val {splitted_set['val_set'].value_counts()[1]}")
print(f"test {splitted_set['test_set'].value_counts()[1]}")

train 2868
val 364
test 359

In [13]:
splitted_set[splitted_set['train_set']==1]

,location,swing_type,frame_type,src_video,frame_path,label_path,train_set,val_set,test_set
0,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_234030_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,1,0,0
1,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_234108_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,1,0,0
2,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_234255_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,1,0,0
3,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_234030_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,1,0,0
4,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233910_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,1,0,0
...,...,...,...,...,...,...,...,...,...
3496,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_221643_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,1,0,0
3497,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_220416_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,1,0,0
3498,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_222202_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,1,0,0
3499,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_222352_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,1,0,0
3500,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_222352_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,1,0,0

In [14]:
splitted_set[splitted_set['val_set']==1]

,location,swing_type,frame_type,src_video,frame_path,label_path,train_set,val_set,test_set
425,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233819_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,1,0
426,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,1,0
427,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233819_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,1,0
428,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233610_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,1,0
429,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233718_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,1,0
...,...,...,...,...,...,...,...,...,...
3541,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_221643_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,1,0
3542,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_222202_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,1,0
3543,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_220240_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,1,0
3544,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_220725_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,1,0
3545,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_220240_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,1,0

In [15]:
splitted_set[splitted_set['test_set']==1]

,location,swing_type,frame_type,src_video,frame_path,label_path,train_set,val_set,test_set
378,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_234030_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,1
379,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_234255_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,1
380,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233910_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,1
381,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233642_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,1
382,KP_Common_Area,Flighted,None_Strike_frames,20250304_t_233910_sink,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,Golf_Ball_Flighted_data_labelled_final\KP_Comm...,0,0,1
...,...,...,...,...,...,...,...,...,...
3586,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_220416_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,0,1
3587,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_222352_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,0,1
3588,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_221643_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,0,1
3589,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_222352_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,0,1
3590,PR_Library_Top_Floor,Putting,Strike_frames,20250304_t_221906_sink,Golf_Ball_Putting_data_labelled_final\PR_Libra...,Golf_Ball_Putting_data_labelled_final\PR_Libra...,0,0,1

In [17]:
splitted_set.to_csv("baseline_dataset.csv")